import 'dotenv/config';
import { prisma } from '@/db/prisma';

const routes = [
  {
    routeNumber: 1,
    title: 'Bo. Obrero, Lapuz to City Proper',
    duration: '25 mins',
    description: 'Loop route via Everlasting St. and Margarita St., connects Lapuz to City Proper.',
    color: '#16a34a',
    fare: '₱13.00',
    distance: '4.8 km',
    category: 'loop',
    path: [[10.7130, 122.5830], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Bo. Obrero Gym', to: 'Everlasting St.', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'Margarita St.', to: 'City Proper', duration: '15 mins', order: 1 },
    ],
  },
  {
    routeNumber: 2,
    title: 'Villa Plaza to City Proper via Calumpang',
    duration: '28 mins',
    description: 'Connects Villa Anita/Plaza area to downtown via Calumpang.',
    color: '#f59e0b',
    fare: '₱14.00',
    distance: '5.5 km',
    category: 'recommended',
    path: [[10.7420, 122.5720], [10.7300, 122.5750], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Villa Plaza', to: 'Calumpang', duration: '14 mins', order: 0 },
      { mode: 'Jeepney', from: 'Calumpang', to: 'City Proper', duration: '14 mins', order: 1 },
    ],
  },
  {
    routeNumber: 3,
    title: 'Ungka to City Proper via CPU',
    duration: '32 mins',
    description: 'Loop route passing Central Philippine University campus.',
    color: '#0ea5e9',
    fare: '₱15.00',
    distance: '6.9 km',
    category: 'loop',
    path: [[10.7420, 122.5590], [10.7280, 122.5430], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Ungka Terminal', to: 'CPU', duration: '12 mins', order: 0 },
      { mode: 'Jeepney', from: 'CPU', to: 'City Proper', duration: '20 mins', order: 1 },
    ],
  },
  {
    routeNumber: 4,
    title: 'Ungka to City Proper via B. Aquino Ave. / Festive Walk',
    duration: '30 mins',
    description: 'Loop route through the business district via Festive Walk Transport Hub.',
    color: '#a855f7',
    fare: '₱15.00',
    distance: '7.1 km',
    category: 'loop',
    path: [[10.7420, 122.5590], [10.7300, 122.5460], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Ungka Terminal', to: 'Festive Walk', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'B. Aquino Ave.', to: 'City Proper', duration: '20 mins', order: 1 },
    ],
  },
  {
    routeNumber: 5,
    title: 'Festive Walk to City Proper via B. Aquino Ave. and SM City',
    duration: '26 mins',
    description: 'Passes Festive Walk Transport Hub, Zuri Hotel, Plazuela, and SM City.',
    color: '#ef4444',
    fare: '₱14.00',
    distance: '6.0 km',
    category: 'recommended',
    path: [[10.7300, 122.5460], [10.7100, 122.5580], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Festive Walk Hub', to: 'SM City', duration: '12 mins', order: 0 },
      { mode: 'Jeepney', from: 'SM City', to: 'City Proper', duration: '14 mins', order: 1 },
    ],
  },
  {
    routeNumber: 6,
    title: 'Lanit to SM City via Infante',
    duration: '24 mins',
    description: 'Connects Lanit/Leganes boundary to SM City through Infante St.',
    color: '#16a34a',
    fare: '₱13.00',
    distance: '5.2 km',
    category: 'recommended',
    path: [[10.7600, 122.5450], [10.7100, 122.5580]],
    segments: [
      { mode: 'Jeepney', from: 'Lanit Boundary', to: 'Infante St.', duration: '14 mins', order: 0 },
      { mode: 'Jeepney', from: 'Infante St.', to: 'SM City', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 7,
    title: 'Compania to City Proper',
    duration: '22 mins',
    description: 'Loop route connecting Compania to downtown Iloilo.',
    color: '#f59e0b',
    fare: '₱13.00',
    distance: '4.5 km',
    category: 'loop',
    path: [[10.7280, 122.5350], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Compania', to: 'City Proper', duration: '22 mins', order: 0 },
    ],
  },
  {
    routeNumber: 8,
    title: 'Parola to SM City via Infante',
    duration: '20 mins',
    description: 'Loop route from Parola area to SM City through Infante St.',
    color: '#0ea5e9',
    fare: '₱13.00',
    distance: '4.2 km',
    category: 'loop',
    path: [[10.7220, 122.5860], [10.7100, 122.5580]],
    segments: [
      { mode: 'Jeepney', from: 'Parola', to: 'Infante St.', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'Infante St.', to: 'SM City', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 9,
    title: 'Mohon to City Proper',
    duration: '23 mins',
    description: 'Loop route via Osmeña St. and Plaza Arevalo, connecting Mohon to downtown.',
    color: '#a855f7',
    fare: '₱13.00',
    distance: '4.9 km',
    category: 'loop',
    path: [[10.6880, 122.5630], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Mohon Terminal', to: 'Osmeña St.', duration: '8 mins', order: 0 },
      { mode: 'Jeepney', from: 'Plaza Arevalo', to: 'City Proper', duration: '15 mins', order: 1 },
    ],
  },
  {
    routeNumber: 10,
    title: 'Buntatala / Tagbak Terminal to City Proper',
    duration: '27 mins',
    description: 'Loop via Spousal of Mary and Joseph Parish, MacArthur Dr., and C. Aquino Ave.',
    color: '#ef4444',
    fare: '₱14.00',
    distance: '6.2 km',
    category: 'loop',
    path: [[10.7550, 122.5600], [10.7100, 122.5750], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Tagbak Terminal', to: 'MacArthur Dr.', duration: '15 mins', order: 0 },
      { mode: 'Jeepney', from: 'C. Aquino Ave.', to: 'City Proper', duration: '12 mins', order: 1 },
    ],
  },
  {
    routeNumber: 11,
    title: 'Ticud, La Paz to City Proper',
    duration: '18 mins',
    description: 'Loop route connecting Ticud, La Paz to downtown Iloilo.',
    color: '#16a34a',
    fare: '₱12.00',
    distance: '3.6 km',
    category: 'loop',
    path: [[10.7180, 122.5680], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Ticud', to: 'City Proper', duration: '18 mins', order: 0 },
    ],
  },
  {
    routeNumber: 12,
    title: 'Mandurriao to City Proper via Festive Walk / B. Aquino Ave.',
    duration: '29 mins',
    description: 'Passes Mandurriao Plaza, R. Mapa St., and the Mandurriao business district.',
    color: '#f59e0b',
    fare: '₱15.00',
    distance: '6.5 km',
    category: 'recommended',
    path: [[10.7040, 122.5460], [10.7300, 122.5460], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Mandurriao Plaza', to: 'Festive Walk', duration: '14 mins', order: 0 },
      { mode: 'Jeepney', from: 'B. Aquino Ave.', to: 'City Proper', duration: '15 mins', order: 1 },
    ],
  },
  {
    routeNumber: 13,
    title: 'Hibao-an to City Proper via Tabucan Hub',
    duration: '26 mins',
    description: 'Loop via Tabucan Transport Hub connecting Hibao-an to downtown.',
    color: '#0ea5e9',
    fare: '₱14.00',
    distance: '5.9 km',
    category: 'loop',
    path: [[10.7460, 122.5300], [10.7300, 122.5350], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Hibao-an', to: 'Tabucan Hub', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'Tabucan Hub', to: 'City Proper', duration: '16 mins', order: 1 },
    ],
  },
  {
    routeNumber: 14,
    title: 'Hibao-an to Jaro via B. Aquino Ave. / Festive Walk',
    duration: '20 mins',
    description: 'Loop connecting Hibao-an directly to Jaro district through Festive Walk.',
    color: '#a855f7',
    fare: '₱13.00',
    distance: '4.3 km',
    category: 'loop',
    path: [[10.7460, 122.5300], [10.7300, 122.5460], [10.7307, 122.5634]],
    segments: [
      { mode: 'Jeepney', from: 'Hibao-an', to: 'Festive Walk', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'B. Aquino Ave.', to: 'Jaro Plaza', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 15,
    title: 'Molo to City Proper via Baluarte',
    duration: '19 mins',
    description: 'Loop route passing Baluarte, connecting Molo district to downtown.',
    color: '#ef4444',
    fare: '₱12.00',
    distance: '3.9 km',
    category: 'loop',
    path: [[10.6889, 122.5478], [10.6940, 122.5580], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Molo Plaza', to: 'Baluarte', duration: '8 mins', order: 0 },
      { mode: 'Jeepney', from: 'Baluarte', to: 'City Proper', duration: '11 mins', order: 1 },
    ],
  },
  {
    routeNumber: 16,
    title: 'Bito-on to Jaro via Balabago',
    duration: '24 mins',
    description: 'Loop route connecting Bito-on to Jaro through Balabago.',
    color: '#16a34a',
    fare: '₱13.00',
    distance: '5.3 km',
    category: 'loop',
    path: [[10.6870, 122.5350], [10.7150, 122.5400], [10.7307, 122.5634]],
    segments: [
      { mode: 'Jeepney', from: 'Bito-on', to: 'Balabago', duration: '14 mins', order: 0 },
      { mode: 'Jeepney', from: 'Balabago', to: 'Jaro Plaza', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 17,
    title: 'Villa Baybay to City Proper via Bonifacio',
    duration: '17 mins',
    description: 'Connects the coastal Villa Baybay area to downtown via Bonifacio St.',
    color: '#f59e0b',
    fare: '₱12.00',
    distance: '3.5 km',
    category: 'recommended',
    path: [[10.6800, 122.5610], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Villa Baybay', to: 'Bonifacio St.', duration: '9 mins', order: 0 },
      { mode: 'Jeepney', from: 'Bonifacio St.', to: 'City Proper', duration: '8 mins', order: 1 },
    ],
  },
  {
    routeNumber: 18,
    title: 'Tagbak to City Proper via Coastal Road',
    duration: '31 mins',
    description: 'Loop route via Coastal Rd., Lapuz Mansaya-Loboc Rd., and the Iloilo-Bacolod Ferry Terminal.',
    color: '#0ea5e9',
    fare: '₱15.00',
    distance: '7.4 km',
    category: 'loop',
    path: [[10.7550, 122.5600], [10.7300, 122.5900], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Tagbak Terminal', to: 'Coastal Rd.', duration: '18 mins', order: 0 },
      { mode: 'Jeepney', from: 'Ferry Terminal Rd.', to: 'City Proper', duration: '13 mins', order: 1 },
    ],
  },
  {
    routeNumber: 19,
    title: 'Bito-on to City Proper via La Paz',
    duration: '25 mins',
    description: 'Loop route connecting Bito-on to downtown through La Paz district.',
    color: '#a855f7',
    fare: '₱14.00',
    distance: '5.6 km',
    category: 'loop',
    path: [[10.6870, 122.5350], [10.7160, 122.5730], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Bito-on', to: 'La Paz', duration: '15 mins', order: 0 },
      { mode: 'Jeepney', from: 'La Paz', to: 'City Proper', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 20,
    title: 'Mohon to Jaro via SO OC / Festive Walk / ISATU',
    duration: '28 mins',
    description: 'Connects Mohon to Jaro, passing ISATU and Festive Walk.',
    color: '#ef4444',
    fare: '₱14.00',
    distance: '6.1 km',
    category: 'recommended',
    path: [[10.6880, 122.5630], [10.7100, 122.5450], [10.7307, 122.5634]],
    segments: [
      { mode: 'Jeepney', from: 'Mohon', to: 'ISATU', duration: '16 mins', order: 0 },
      { mode: 'Jeepney', from: 'Festive Walk', to: 'Jaro Plaza', duration: '12 mins', order: 1 },
    ],
  },
  {
    routeNumber: 21,
    title: 'Tagbak / Buntatala to Festive Walk via SM City / Atria',
    duration: '22 mins',
    description: 'Passes MacArthur Dr., SM Savemore Quintin Salas, and Atria Park District.',
    color: '#16a34a',
    fare: '₱13.00',
    distance: '4.8 km',
    category: 'recommended',
    path: [[10.7550, 122.5600], [10.7100, 122.5580], [10.7300, 122.5460]],
    segments: [
      { mode: 'Jeepney', from: 'Tagbak Terminal', to: 'SM Savemore', duration: '12 mins', order: 0 },
      { mode: 'Jeepney', from: 'Atria Park', to: 'Festive Walk', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 22,
    title: 'Ungka to La Paz via CPU – ISATU',
    duration: '21 mins',
    description: 'Loop route connecting Ungka to La Paz through CPU and ISATU.',
    color: '#f59e0b',
    fare: '₱13.00',
    distance: '4.7 km',
    category: 'loop',
    path: [[10.7420, 122.5590], [10.7280, 122.5430], [10.7160, 122.5730]],
    segments: [
      { mode: 'Jeepney', from: 'Ungka Terminal', to: 'CPU', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'ISATU', to: 'La Paz', duration: '11 mins', order: 1 },
    ],
  },
  {
    routeNumber: 23,
    title: 'Mohon to Mandurriao Business District',
    duration: '16 mins',
    description: 'Direct route connecting Mohon to the Mandurriao business district.',
    color: '#0ea5e9',
    fare: '₱12.00',
    distance: '3.3 km',
    category: 'recommended',
    path: [[10.6880, 122.5630], [10.7040, 122.5460]],
    segments: [
      { mode: 'Jeepney', from: 'Mohon', to: 'Mandurriao Plaza', duration: '16 mins', order: 0 },
    ],
  },
  {
    routeNumber: 24,
    title: 'La Paz to Festive Walk via Nabitasan',
    duration: '20 mins',
    description: 'Loop route connecting La Paz to Festive Walk through Nabitasan.',
    color: '#a855f7',
    fare: '₱13.00',
    distance: '4.4 km',
    category: 'loop',
    path: [[10.7160, 122.5730], [10.7150, 122.5550], [10.7300, 122.5460]],
    segments: [
      { mode: 'Jeepney', from: 'La Paz', to: 'Nabitasan', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'Nabitasan', to: 'Festive Walk', duration: '10 mins', order: 1 },
    ],
  },
  {
    routeNumber: 25,
    title: 'Molo to City Proper via General Luna',
    duration: '18 mins',
    description: 'Loop route via General Luna St., connecting Molo district to downtown.',
    color: '#ef4444',
    fare: '₱12.00',
    distance: '3.7 km',
    category: 'loop',
    path: [[10.6889, 122.5478], [10.6963, 122.5726], [10.6980, 122.5720]],
    segments: [
      { mode: 'Jeepney', from: 'Molo Plaza', to: 'General Luna St.', duration: '10 mins', order: 0 },
      { mode: 'Jeepney', from: 'General Luna St.', to: 'City Proper', duration: '8 mins', order: 1 },
    ],
  },
];

async function main() {
  console.log(`Seeding ${routes.length} routes...`);

  for (const { segments, ...routeData } of routes) {
    await prisma.route.upsert({
      where: { routeNumber: routeData.routeNumber },
      update: {
        ...routeData,
        segments: { deleteMany: {}, create: segments },
      },
      create: {
        ...routeData,
        segments: { create: segments },
      },
    });
  }

  const total = await prisma.route.count();
  console.log(`Done. ${total} routes in the database.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
